/**
 * Domain types.
 *
 * These used to be generated by Prisma. With Mongoose there is no codegen step,
 * so the enums are declared here as the single source of truth — Mongoose
 * validates against them at the schema level, and TypeScript narrows against
 * them everywhere else.
 *
 * Safe to import from Client Components: no secrets, no database driver.
 */

/* ------------------------------------------------------------------ */
/* Enums                                                               */
/* ------------------------------------------------------------------ */

export const SubscriptionStatus = {
  incomplete: "incomplete",
  incomplete_expired: "incomplete_expired",
  trialing: "trialing",
  active: "active",
  past_due: "past_due",
  canceled: "canceled",
  unpaid: "unpaid",
  paused: "paused",
} as const;
export type SubscriptionStatus =
  (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const PaymentType = {
  one_time: "one_time",
  subscription: "subscription",
  marketplace: "marketplace",
} as const;
export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType];

export const PaymentStatus = {
  pending: "pending",
  requires_action: "requires_action",
  succeeded: "succeeded",
  failed: "failed",
  refunded: "refunded",
  partially_refunded: "partially_refunded",
} as const;
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

export const RefundStatus = {
  pending: "pending",
  succeeded: "succeeded",
  failed: "failed",
  canceled: "canceled",
} as const;
export type RefundStatus = (typeof RefundStatus)[keyof typeof RefundStatus];

export const WebhookStatus = {
  processed: "processed",
  failed: "failed",
  ignored: "ignored",
} as const;
export type WebhookStatus = (typeof WebhookStatus)[keyof typeof WebhookStatus];

export const AccessReason = {
  one_time_payment: "one_time_payment",
  subscription_active: "subscription_active",
  payment_failed: "payment_failed",
  refunded: "refunded",
  subscription_canceled: "subscription_canceled",
  dunning_exhausted: "dunning_exhausted",
  never_granted: "never_granted",
} as const;
export type AccessReason = (typeof AccessReason)[keyof typeof AccessReason];

export const values = <T extends Record<string, string>>(e: T): string[] =>
  Object.values(e);

/* ------------------------------------------------------------------ */
/* Plain shapes crossing the server → client boundary.                 */
/* Mongoose documents are not serialisable (ObjectId, methods), so     */
/* every service returns one of these instead of a raw document.       */
/* ------------------------------------------------------------------ */

export interface Customer {
  id: string;
  sessionId: string;
  stripeCustomerId: string | null;
  email: string | null;
  connectAccountId: string | null;
  connectOnboarded: boolean;
  createdAt: Date;
}

export interface Subscription {
  id: string;
  stripeSubId: string;
  customerId: string;
  plan: string;
  stripePriceId: string | null;
  status: SubscriptionStatus;
  currentPeriodEnd: Date | null;
  cancelAtPeriodEnd: boolean;
  canceledAt: Date | null;
  createdAt: Date;
}

export interface Payment {
  id: string;
  stripePaymentIntentId: string;
  customerId: string;
  amount: number;
  currency: string;
  status: PaymentStatus;
  type: PaymentType;
  description: string | null;
  failureCode: string | null;
  failureMessage: string | null;
  platformFee: number | null;
  sellerPayout: number | null;
  connectAccountId: string | null;
  amountRefunded: number;
  createdAt: Date;
}

export interface Refund {
  id: string;
  stripeRefundId: string;
  paymentId: string;
  amount: number;
  status: RefundStatus;
  reason: string | null;
  createdAt: Date;
}

export interface Access {
  granted: boolean;
  reason: AccessReason;
  grantedAt: Date | null;
  revokedAt: Date | null;
}
