import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate` — not ours to lint.
    "src/generated/**",
  ]),

  {
    rules: {
      // `useActionState` actions must accept a leading previous-state argument
      // even when they don't read it, so a leading underscore means "required
      // by the signature, deliberately unused" rather than "dead code".
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
    },
  },
]);

export default eslintConfig;
